results_dir: sert_results
cpu_metrics_dir: cpu_data
test_settings: test_settings.csv
temp_dir: temp_dir
data_file: all_data.csv
overwrite_data: false

influxdb:
    user: root
    password: root
    tunnel-database: sensors
    host: localhost
    port: 8086

whitelist:
    sert-XXX1,
    sert-XXX2,
    sert-XXX3  